spring:
  mustache:
    servlet:
      expose-request-attributes: true
logging:
  level:
    com.example.demo: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web: TRACE
    org.springframework.web.reactive: TRACE
